### PR TITLE
Update entrypoint script to deal with fresh DB instances

### PR DESCRIPTION
**Pull request by mathieupotier**
This is for fixing new DB instance that are empty.
It calls the refreshall script in order to build the DB schema.

### CODE REVIEW

**Comment by mgodlewski** [comment]
Hi,

Can you rebase on master ?
The current pull request have commits from #1 

Regards,

Mathieu

**Comment by mathieupotier** [comment]
Are you sure, I had rebased it by yesterday evening, it should be fine now.

In Dockerfile, there was a `tab` instead of `spaces`, I changed it to `spaces`
In Entrypoint, I reviewed the script to add steps when `DIACAMMA_DATABASE` env var is provided.

**Comment by mathieupotier** [comment]
I squashed changes and rebased from origin/master

**Comment by mgodlewski** [comment]
Thank you.
I do not like the "wait" line but do not have better recommandation.

If I understand well, refreshall is in charge of the database migration on version upgrade.

**Pull request merged**
